# Generated by Django 5.2.4 on 2025-07-24 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catygory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'катигория',
                'verbose_name_plural': 'катигория',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Тег',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('descriptions', models.TextField(blank=True, default='по умол. описание', null=True, verbose_name='описание')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата добавление')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='дата изменение')),
                ('author', models.CharField(blank=True, max_length=50, null=True, verbose_name='автор')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='посмотры')),
                ('is_published', models.BooleanField(default=True, verbose_name='публичность')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/photos', verbose_name='фото')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='blog.catygory', verbose_name='Кат')),
                ('tags', models.ManyToManyField(blank=True, null=True, related_name='new', to='blog.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'новости',
                'verbose_name_plural': 'новости',
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/photos', verbose_name='фото')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.news', verbose_name='новости')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
    ]
