# Generated by Django 5.2.4 on 2025-07-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='news', to='blog.tag', verbose_name='Теги'),
        ),
    ]
