# Generated by Django 5.2.4 on 2025-07-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='просмотры'),
        ),
    ]
