# Generated by Django 5.2.4 on 2025-08-02 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_news_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catygory',
            new_name='Category',
        ),
    ]
