# Generated by Django 5.2.4 on 2025-08-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_catygory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='news', to='blog.tag', verbose_name='Теги'),
        ),
    ]
