# Generated by Django 5.2.4 on 2025-08-03 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_news_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='descriptions',
            new_name='description',
        ),
    ]
